###
GET http://localhost:5211/fishes

###
GET http://localhost:5211/fishes?name=Angel

###
GET http://localhost:5211/fishes?pageSize=

###
GET http://localhost:5211/fishes?pageSize=3&pageNumber=2

###
GET http://localhost:5211/types

###
GET http://localhost:5211/fishes/4e139382-e660-4d7d-b1ce-b84d648dc795

###
POST http://localhost:5211/fishes
Content-Type: application/json

{
    "name":"Neon Tetra",
    "fishTypeId":"6a39de98-5427-4b60-8d4a-fd7955b4abfe",
    "habitat":"Southest Asia",
    "maxSizeInInches":1.5,
    "description":"Known for their vibrant blue and red stripes, neon tetras are peaceful schooling fish ideal for community tanks. They thrive in soft, acidic water and prefer to be kept in groups of six or more.",
    "price":3.0,
    "koiFish":false
}

###
PUT http://localhost:5211/fishes/4e139382-e660-4d7d-b1ce-b84d648dc795
Content-Type: application/json

{
    "name":"Testing fish",
    "fishTypeId":"51FB4E2F-0DE0-43D8-89A6-81A481586EFA",
    "habitat":"Global",
    "maxSizeInInches":2.5,
    "description":"Testing description.",
    "price":10.0,
    "koiFish":true
}

###
DELETE http://localhost:5211/fishes/4e139382-e660-4d7d-b1ce-b84d648dc795