###
GET http://localhost:5211/fishes

###
GET http://localhost:5211/types

###
GET http://localhost:5211/fishes/924fc91c-06b9-445f-8356-2eaa15a2ed2f
###
POST http://localhost:5211/fishes
Content-Type: application/json

{
    "name":"fhdf",
    "FishTypeId":"4698dc77-d875-4a7b-8a2f-42d4db48e4fd",
    "habitat":"fefe",
    "maxSizeInInInches":3.0,
    "description":"this is the description",
    "price":9.1,
    "koiFish":false
}

###
PUT http://localhost:5211/fishes/924fc91c-06b9-445f-8356-2eaa15a2ed2f
Content-Type: application/json

{
    "name":"Beta new Testing",
    "FishTypeId":"4698dc77-d875-4a7b-8a2f-42d4db48e4fd",
    "habitat":"Saltwater",
    "maxSizeInInInches":3.0,
    "description":"this is the description of ABC",
    "price":9.1,
    "koiFish":false
}

###
DELETE http://localhost:5211/fishes/924fc91c-06b9-445f-8356-2eaa15a2ed2f